name: Check and Set Static IP Task8

on:
  workflow_call:

jobs:
  check-static-ip:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Check and Convert Public IP to Static if needed
        run: |
          RESOURCE_GROUP="rg-devops-lab"
          VM_NAME="Linux-VM01"

          echo "Getting NIC name from VM..."
          NIC_NAME=$(az vm show \
            --resource-group "$RESOURCE_GROUP" \
            --name "$VM_NAME" \
            --query "networkProfile.networkInterfaces[0].id" -o tsv | xargs basename)

          echo "NIC Name: $NIC_NAME"

          echo "Getting Public IP ID..."
          IP_ID=$(az network nic show \
            --resource-group "$RESOURCE_GROUP" \
            --name "$NIC_NAME" \
            --query "ipConfigurations[0].publicIpAddress.id" -o tsv)

          if [ -z "$IP_ID" ]; then
            echo "Failed to get Public IP ID. Aborting."
            exit 1
          fi

          IP_NAME=$(basename "$IP_ID")
          echo "🌐 Public IP Name: $IP_NAME"

          echo "🔍 Checking current allocation method..."
          ALLOCATION=$(az network public-ip show \
            --resource-group "$RESOURCE_GROUP" \
            --name "$IP_NAME" \
            --query "publicIpAllocationMethod" -o tsv)

          echo "Allocation method: $ALLOCATION"

          if [ "$ALLOCATION" = "Dynamic" ]; then
            echo "Converting to Static IP..."
            az network public-ip update \
              --resource-group "$RESOURCE_GROUP" \
              --name "$IP_NAME" \
              --allocation-method Static
            echo "IP has been updated to Static."
          else
            echo "IP is already Static. No changes needed."
          fi
