name: Check and Convert Public IP to Static

on:
  workflow_call:
  workflow_dispatch:

jobs:
  check-static-ip:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get Public IP Name
        id: get_ip_name
        run: |
          RESOURCE_GROUP="rg-devops-lab"

          IP_NAME=$(az network public-ip list \
            --resource-group "$RESOURCE_GROUP" \
            --query "[0].name" -o tsv)

          echo "IP_NAME=$IP_NAME" >> $GITHUB_ENV
          echo "IP name found: $IP_NAME"

      - name: Check and Update IP Allocation
        run: |
          RESOURCE_GROUP="rg-devops-lab"

          ALLOCATION=$(az network public-ip show \
            --resource-group "$RESOURCE_GROUP" \
            --name "$IP_NAME" \
            --query "publicIpAllocationMethod" -o tsv)

          echo "Current IP allocation: $ALLOCATION"

          if [ "$ALLOCATION" = "Dynamic" ]; then
            echo "Changing allocation to Static..."
            az network public-ip update \
              --resource-group "$RESOURCE_GROUP" \
              --name "$IP_NAME" \
              --allocation-method Static
            echo "Allocation changed to Static."
          else
            echo "Allocation already Static. No action needed."
          fi

      - name: Get VM Public IP
        id: get_vm_ip
        run: |
          RESOURCE_GROUP="rg-devops-lab"
          VM_NAME="Linux-VM01"

          VM_IP=$(az vm show -d \
            --resource-group "$RESOURCE_GROUP" \
            --name "$VM_NAME" \
            --query publicIps -o tsv)

          echo "VM_IP=$VM_IP" >> $GITHUB_ENV
          echo "Public VM IP: $VM_IP"
