name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test-e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Create .env file
        run: |
          echo "PORT=3001" >> .env
          echo "FRONTEND_PORT=3000" >> .env
          echo "MONGO_HOST=mongo" >> .env
          echo "MONGO_PORT=27017" >> .env
          echo "MONGO_DB=testdb" >> .env
          echo "MONGO_INITDB_ROOT_USERNAME=admin" >> .env
          echo "MONGO_INITDB_ROOT_PASSWORD=admin123" >> .env

      - name: Build and start services
        run: docker-compose up -d --build

      - name: Wait for containers to be healthy
        run: |
          sleep 5
          docker-compose ps
          docker inspect --format='{{json .State.Health}}' task7_daily-backend-1

      - name: Run backend tests
        run: docker-compose exec backend npm test

      - name: Collect logs if tests fail
        if: failure()
        run: |
          docker-compose logs > docker-logs.txt

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: docker-logs
          path: docker-logs.txt

      - name: Shut down
        run: docker-compose down