name: CI/CD Pipeline Task8

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:

  frontend-tests:
    uses: ./.github/workflows/frontend-test-task8.yml
  
  backend-tests:
    uses: ./.github/workflows/backend-test-task8.yml

  docker-up:
    needs: [frontend-tests, backend-tests]
    uses: ./.github/workflows/docker-compose-up-task8.yml
    secrets: inherit

  notify:
    needs: [backend-tests, frontend-tests, docker-up]
    if: always()
    uses: ./.github/workflows/notify-task8.yml
    with:
      job_start_time: ${{ needs.frontend-tests.outputs.job_start_time }}
      backend_test_status: ${{ needs.backend-tests.result }}
      frontend_test_status: ${{ needs.frontend-tests.result }}
      backend_health: ${{ needs.docker-up.outputs.backend_health }}
      frontend_health: ${{ needs.docker-up.outputs.frontend_health }}
    secrets: inherit

  deploy:
    name: Deploy to Azure VM
    needs: [frontend-tests, backend-tests]
    if: ${{ needs.frontend-tests.result == 'success' && needs.backend-tests.result == 'success' }}
    uses: ./.github/workflows/deploy-task8.yml
    secrets: inherit

  create-and-attach-disk:
    needs: deploy
    uses: ./.github/workflows/createa-disk-attach.yml
    secrets: inherit
