name: CI/CD Pipeline Task8

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:

  frontend-tests:
    uses: ./.github/workflows/frontend-test-task8.yml
  
  backend-tests:
    uses: ./.github/workflows/backend-test-task8.yml

  docker-up:
    needs: [frontend-tests, backend-tests]
    uses: ./.github/workflows/docker-up-task8.yml
    secrets: inherit
