- name: Download Deployment Log
  uses: actions/download-artifact@v4
  with:
    name: terraform-deployment-log

- name: Commit Deployment Log
  run: |
    git config user.name "github-actions[bot]"
    git config user.email "github-actions[bot]@users.noreply.github.com"
    git add deployment_log.md
    git commit -m "Add Terraform deployment log"
    git push || echo "No changes to commit"

