name: Docker Compose Up Task8

on:
  workflow_call:

jobs:
  docker-up:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: week8/week8_summery/app

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create .env file from GitHub Secret
        run: echo "${{ secrets.ENV_FILE_TASK8 }}" > .env

      - name: Docker Compose Up
        run: |
          docker compose -f docker-compose.yml up -d --build

      - name: Wait for Webapp to be healthy
        id: wait_for_health
        run: |
          echo "Waiting for webapp container to be healthy..."
          FINAL_HEALTH_STATUS="unknown"
          max_retries=18  # 18 * 10s = 180s

          for i in $(seq 1 $max_retries); do
            status=$(docker inspect webapp --format '{{.State.Health.Status}}' 2>/dev/null || echo "not_found")

            echo "[$i/$max_retries] Status: $status"
            docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"

            if [ "$status" = "healthy" ]; then
              echo "webapp is healthy!"
              FINAL_HEALTH_STATUS="healthy"
              break
            elif [ "$status" = "not_found" ]; then
              echo "webapp not found. Retrying..."
            else
              echo "webapp status: $status. Waiting..."
            fi

            sleep 10
          done

          if [ "$FINAL_HEALTH_STATUS" != "healthy" ]; then
            echo "webapp did not become healthy in time."
            docker logs webapp || echo "No logs available."
            FINAL_HEALTH_STATUS="unhealthy"
            exit 1
          fi

          echo "health_status=$FINAL_HEALTH_STATUS" >> "$GITHUB_OUTPUT"
