name: Docker Compose Up Task8

on:
  workflow_call:

jobs:
  up:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: week8/week8_summery/app

    steps:
      - uses: actions/checkout@v4

      - name: Docker Compose Up
        run: |
          docker-compose -f docker compose.yml up -d --build
