name: Check and Set Static Public IP

on:
  workflow_dispatch:
  workflow_call:

jobs:
  check-and-set-ip:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get Public IP Allocation Method
        id: get_ip
        run: |
          IP_NAME=$(az vm show \
            --resource-group rg-devops-lab \
            --name Linux-VM01 \
            --query 'networkProfile.networkInterfaces[0].id' -o tsv | \
            xargs az network nic show --query "ipConfigurations[0].publicIpAddress.id" -o tsv | \
            xargs az network public-ip show --query "name" -o tsv)

          ALLOCATION=$(az network public-ip show \
            --resource-group RG-DEVOPS-LAB \
            --name $IP_NAME \
            --query "publicIpAllocationMethod" -o tsv)

          echo "Public IP Name: $IP_NAME"
          echo "Allocation method: $ALLOCATION"

          echo "ip_name=$IP_NAME" >> $GITHUB_OUTPUT
          echo "allocation=$ALLOCATION" >> $GITHUB_OUTPUT

      - name: Set IP to Static if Not Static
        if: steps.get_ip.outputs.allocation != 'Static'
        run: |
          az network public-ip update \
            --resource-group RG-DEVOPS-LAB \
            --name ${{ steps.get_ip.outputs.ip_name }} \
            --allocation-method Static
